import type { Advisor, Lead } from "./types";

export const ADVISORS: Advisor[] = [
  {
    id: "adv-growth-1",
    name: "Aanya Mehta",
    role: "growth",
    territories: ["Delhi", "Gurugram"],
  },
  {
    id: "adv-acq-1",
    name: "Ishaan Khanna",
    role: "acquisition",
    territories: ["Delhi", "Gurugram", "Mumbai"],
  },
];

function daysAgo(d: number): string {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();
}

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
}

/** Sample leads matching the reference Lead Intelligence Dashboard shape. */
export const INITIAL_LEADS: Lead[] = [
  {
    id: "lead-001",
    name: "Priya & Arjun Malhotra",
    phone: "+91 98100 11223",
    email: "priya.malhotra@email.com",
    source: "Website",
    businessUnit: "EE",
    projectType: "residential",
    location: "Vasant Vihar, New Delhi",
    territory: "Delhi",
    budgetIndication: "₹2–3 Cr design+build",
    capturedAt: hoursAgo(6),
    qualification: "Hot",
    stage: "handed_to_acquisition",
    assignedAdvisorId: "adv-acq-1",
    lastFollowUpAt: hoursAgo(2),
    firstContactedAt: hoursAgo(4),
    priorEngagement: true,
    crossSell: false,
    signed: false,
  },
  {
    id: "lead-002",
    name: "Nexus Holdings Pvt Ltd",
    phone: "+91 98765 44321",
    email: "facilities@nexusholdings.in",
    source: "Website",
    businessUnit: "EE",
    projectType: "corporate",
    location: "BKC, Mumbai",
    territory: "Mumbai",
    budgetIndication: "₹80L–1.2 Cr design fee",
    capturedAt: daysAgo(18),
    qualification: "Warm",
    stage: "proposal_sent",
    assignedAdvisorId: "adv-acq-1",
    lastFollowUpAt: daysAgo(2),
    firstContactedAt: daysAgo(17),
    priorEngagement: false,
    crossSell: false,
    signed: false,
  },
  {
    id: "lead-003",
    name: "Kabir Desai",
    phone: "+91 90011 22334",
    email: "kabir.d@email.com",
    source: "Instagram",
    businessUnit: "EH",
    projectType: "residential",
    location: "DLF Phase 5, Gurugram",
    territory: "Gurugram",
    capturedAt: daysAgo(5),
    qualification: "Warm",
    stage: "contacted",
    assignedAdvisorId: "adv-growth-1",
    lastFollowUpAt: daysAgo(4),
    firstContactedAt: daysAgo(4),
    priorEngagement: false,
    crossSell: false,
    signed: false,
  },
  {
    id: "lead-004",
    name: "The Aurelia Hotel Group",
    phone: "+91 98200 77881",
    email: "projects@aureliahotels.com",
    source: "Website",
    businessUnit: "EE",
    projectType: "hospitality",
    location: "Juhu, Mumbai",
    territory: "Mumbai",
    budgetIndication: "Boutique refresh",
    capturedAt: daysAgo(53),
    qualification: "Hot",
    stage: "accepted",
    assignedAdvisorId: "adv-acq-1",
    lastFollowUpAt: daysAgo(10),
    firstContactedAt: daysAgo(50),
    priorEngagement: false,
    crossSell: false,
    signed: true,
  },
  {
    id: "lead-005",
    name: "Saanvi Rao",
    phone: "+91 99101 55667",
    email: "saanvi.rao@email.com",
    source: "Website",
    businessUnit: "EH",
    projectType: "residential",
    location: "Sultanpur, New Delhi",
    territory: "Delhi",
    capturedAt: daysAgo(12),
    qualification: "Cold",
    stage: "contacted",
    assignedAdvisorId: "adv-growth-1",
    lastFollowUpAt: daysAgo(11),
    firstContactedAt: daysAgo(11),
    priorEngagement: false,
    crossSell: false,
    signed: false,
  },
  {
    id: "lead-006",
    name: "Orbit Retail Spaces",
    phone: "+91 97654 32109",
    email: "ceo@orbitretail.in",
    source: "Website",
    businessUnit: "EE",
    projectType: "commercial",
    location: "Lower Parel, Mumbai",
    territory: "Mumbai",
    capturedAt: daysAgo(30),
    qualification: "Hot",
    stage: "accepted",
    assignedAdvisorId: "adv-acq-1",
    lastFollowUpAt: daysAgo(8),
    firstContactedAt: daysAgo(28),
    priorEngagement: false,
    crossSell: false,
    signed: true,
  },
  {
    id: "lead-007",
    name: "Meera & Vikram Sethi",
    phone: "+91 98887 66554",
    email: "meera.sethi@email.com",
    source: "Instagram",
    businessUnit: "EE",
    projectType: "residential",
    location: "Golf Course Road, Gurugram",
    territory: "Gurugram",
    budgetIndication: "Second home",
    capturedAt: daysAgo(9),
    qualification: "Hot",
    stage: "proposal_draft",
    assignedAdvisorId: "adv-acq-1",
    lastFollowUpAt: daysAgo(1),
    firstContactedAt: daysAgo(8),
    priorEngagement: true,
    crossSell: false,
    signed: false,
  },
  {
    id: "lead-008",
    name: "Indigo Craft Collective",
    phone: "+91 97000 11220",
    email: "hello@indigocraft.co",
    source: "Website",
    businessUnit: "EE",
    projectType: "commercial",
    location: "Shahpur Jat, Delhi",
    territory: "Delhi",
    capturedAt: daysAgo(22),
    qualification: "Warm",
    stage: "qualified",
    assignedAdvisorId: "adv-growth-1",
    lastFollowUpAt: daysAgo(20),
    firstContactedAt: daysAgo(21),
    priorEngagement: false,
    crossSell: false,
    signed: false,
  },
];

export const DESIGN_MANAGEMENT_LINE =
  "When you engage essentia to design your home, you also — by default, and at no separate fee — receive design management: the discipline of keeping that design true, coherent, and correct all the way to the edge of construction. Most firms design and stop at the drawings. We stay as the custodians of the design.";

export const PROJECT_TYPE_VOICE: Record<
  string,
  { tone: string; leadsWith: string; opening: string }
> = {
  residential: {
    tone: "Warm, family-first, emotional",
    leadsWith: 'The fear: "Will it feel like home?"',
    opening:
      "A home is not a finished set of rooms — it is the feeling that greets you at the door, and stays with you long after the drawings are forgotten. essentia designs environments where craftsmanship and calm live in the same breath.",
  },
  corporate: {
    tone: "Data-led, ROI-focused",
    leadsWith: 'The fear: "Every delayed week costs more than the design fee"',
    opening:
      "Workplace design is a commercial instrument. essentia brings design intelligence and executional discipline so your environment accelerates culture, productivity, and brand presence — without the cost of drift.",
  },
  commercial: {
    tone: "Brand-forward, strategic",
    leadsWith: "Positioning and market presence",
    opening:
      "Commercial space is your brand made physical. essentia shapes environments that signal clarity, craft, and intent — spaces that hold their own in a competitive market.",
  },
  hospitality: {
    tone: "Experience-first",
    leadsWith: "Guest experience and revenue performance",
    opening:
      "In hospitality, every surface is part of the guest journey. essentia designs atmospheres that guests remember — and that operators can run with precision.",
  },
};
